// Generated by generate_main 0.0.2
#include <ironforge.hpp>

extern int main(int argc, char* argv[]) {
    (void)argc;
    (void)argv;
    using namespace std;
    using namespace game;

    const auto app_name = strrchr(argv[0], '/') ? strrchr(argv[0], '/') + 1 : nullptr;
    journal::setup_default(string{app_name} + ".log");

    return exec(get_base_path() + "../assets/test/scripts/test.lua");
}